### ISSUE TITLE
Pura finds no devices

### ISSUE THREAD

**Issue by theOrakle** [natekspencer/hacs-pura#11]
As of 7-19, both devices were marked as unavailable.  I deleted the hub and added again as well.

My guess is they changed the API.  pretty much all the entities fail with the same error as below.

2023-07-20 07:46:55.104 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up pura platform for binary_sensor
Traceback (most recent call last):
  File "/opt/homeassistant/3.11.3/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/opt/homeassistant/config/custom_components/pura/binary_sensor.py", line 65, in async_setup_entry
    entities = [
               ^
  File "/opt/homeassistant/config/custom_components/pura/binary_sensor.py", line 71, in <listcomp>
    device_id=device["device_id"],
              ~~~~~~^^^^^^^^^^^^^
KeyError: 'device_id'

**Comment by theOrakle** [comment]
As I hit submit for this ticket, you publish new code...  Nice job!!!
