### ISSUE TITLE
Error Messages on Install

### ISSUE THREAD

**Issue by lux4rd0** [natekspencer/hacs-pura#15]
Hello! I am looking forward to being able to use your Pura add-in... but I am not able to get the first authentication install to complete. Getting these two errors:

```
Logger: pypura.pura
Source: /usr/local/lib/python3.11/site-packages/pypura/pura.py:193
First occurred: August 31, 2023 at 6:10:24 PM (592 occurrences)
Last logged: 7:44:15 AM

Status: 400 - {'message': 'getDevicesAndMigrate() Error'}
```

and

```
This error originated from a custom integration.

Logger: custom_components.pura.coordinator
Source: custom_components/pura/coordinator.py:50
Integration: Pura (documentation, issues)
First occurred: August 31, 2023 at 6:10:24 PM (592 occurrences)
Last logged: 7:44:15 AM

Unknown exception while updating Pura data: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 50, in _async_update_data
    if devices := await self.hass.async_add_executor_job(self.api.get_devices):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 97, in get_devices
    return self.__get("users/devices")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 199, in __get
    return self.__request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 194, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices

```

**Comment by natekspencer** [comment]
They made a new release and some changes that broke things, so I'll have to check later
