### ISSUE TITLE
Error when only one scent is installed

### ISSUE THREAD

**Issue by lux4rd0** [natekspencer/hacs-pura#22]
### The problem

When using the timer service and not selecting a slot (auto-select) - the service fails with this message:

```
Stopped because an error was encountered at September 29, 2023 at 10:11:02 PM (runtime: 0.54 seconds)

500 Server Error: Internal Server Error for url: https://trypura.io/mobile/api/devices/083A8D80C9AC/timer
```

Selecting a non-empty slot works, so does having both slots filled.

### What version of Home Assistant Core are you running?

Home Assistant 2023.9.3

**Comment by natekspencer** [comment]
Can you try [0.1.15b0](https://github.com/natekspencer/hacs-pura/releases/tag/0.1.15b0) and see if that works for you?

**Comment by lux4rd0** [comment]
Grabbed the beta - same issue:

```
Logger: homeassistant.components.automation.pura_loft_on
Source: custom_components/pura/select.py:126
Integration: Automation (documentation, issues)
First occurred: 7:00:30 AM (4 occurrences)
Last logged: 7:01:44 AM

Loft Pura Timer: Error executing script. Unexpected error for call_service at pos 1: 500 Server Error: Internal Server Error for url: https://trypura.io/mobile/api/devices/083A8D80C9AC/timer
While executing automation automation.pura_loft_on
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/pura/select.py", line 126, in async_start_timer
    if await self.hass.async_add_executor_job(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 177, in set_timer
    resp = self.__post(f"devices/{device_id}/timer", json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 203, in __post
    return self.__request("post", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 194, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://trypura.io/mobile/api/devices/083A8D80C9AC/timer

```

**Comment by lux4rd0** [comment]
Cool - downloaded the beta - works great! As a side note - in the service - there's no way to leave the Intensity unchecked... So if I change it in another automation or on the mobile app, this automation needs to be updated as well. Can you make it a check box like the Slot parameter? Thanks!
