### ISSUE TITLE
Error with integration

### ISSUE THREAD

**Issue by lux4rd0** [natekspencer/hacs-pura#27]
### The problem

Getting errors after noticing that my Puras were no longer functional in HA:

```
This error originated from a custom integration.

Logger: custom_components.pura.coordinator
Source: custom_components/pura/coordinator.py:50
Integration: Pura (documentation, issues)
First occurred: 11:55:12 AM (735 occurrences)
Last logged: 6:46:41 PM

Unknown exception while updating Pura data: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 50, in _async_update_data
    if devices := await self.hass.async_add_executor_job(self.api.get_devices):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 97, in get_devices
    return self.__get("users/devices", params={"types": "wall,car,tabletop"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 199, in __get
    return self.__request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 194, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop

```

### What version of Home Assistant Core are you running?

2023.9.3

### What was the last working version of Home Assistant Core?

2023.9.3

**Comment by natekspencer** [comment]
Please update your integration. This has already been resolved.
