### ISSUE TITLE
Exception while updating Pura data - Client Error: Bad Request for URL

### ISSUE THREAD

**Issue by martinkwright** [natekspencer/hacs-pura#28]
### The problem

Integration stopped functioning today around 1 EST and have about 900+ errors in the logs since. Curious if Pura changed something on thier end or if anyone else is seeing this issue. It's been working just fine for quite some time now. 

-----------------------------------------------

Status: 400 - {'message': 'query.types must be car, wall, plus, or 1, 2, 3'}
9:31:28 PM – (ERROR) /usr/local/lib/python3.11/site-packages/pypura/pura.py - message first occurred at 12:54:48 PM and shows up 941 times

-----------------------------------------------

Unknown exception while updating Pura data: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
9:31:28 PM – (ERROR) Pura (custom integration) - message first occurred at 12:54:48 PM and shows up 941 times

### What version of Home Assistant Core are you running?

core-2023.9.3

### What was the last working version of Home Assistant Core?

core-2023.9.3

### Anything in the logs that might be useful?

```txt
Logger: pypura.pura
Source: /usr/local/lib/python3.11/site-packages/pypura/pura.py:193
First occurred: 12:54:48 PM (941 occurrences)
Last logged: 9:31:28 PM

Status: 400 - {'message': 'query.types must be car, wall, plus, or 1, 2, 3'}
Status: 400 - {'message': 'query.types must be car, wall, plus, mini, 1, 2, 3, or 4'}


------------------------------

nknown exception while updating Pura data: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 50, in _async_update_data
    if devices := await self.hass.async_add_executor_job(self.api.get_devices):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 97, in get_devices
    return self.__get("users/devices", params={"types": "wall,car,tabletop"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 199, in __get
    return self.__request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 194, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
```

**Comment by martinkwright** [comment]
Apologies, the update was not displaying. It now that I have restarted HA. Sorry to bother.
