### ISSUE TITLE
New API path?

### ISSUE THREAD

**Issue by derekcentrico** [natekspencer/hacs-pura#70]
### The problem

I haven't had a chance to see if the underlying automations are working (out of town).  But, seems like the API path may have changed and needs updated per log entries.  

### What version of Home Assistant Core are you running?

core-2024.9.2

### Diagnostics information

Unknown exception while updating Pura data: 401 Client Error: Unauthorized for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Cplus
Unknown exception while updating Pura data: 502 Server Error: Bad Gateway for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Cplus
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 50, in _async_update_data
    if devices := await self.hass.async_add_executor_job(self.api.get_devices):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypura/pura.py", line 98, in get_devices
    return self.__get("users/devices", params={"types": "wall,car,plus"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypura/pura.py", line 223, in __get
    return self.__request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypura/pura.py", line 218, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Cplus

**Comment by natekspencer** [comment]
This looks intermittent at the moment. But I do see a new api path that has more data that I'm already working on adding. Thanks!
